apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: scrapyecho:latest
        args: ["-a", "input=testing", "-a", "spiderarg2=whatisz"]
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4

